#!/usr/bin/env python3
"""
Kodiak LLM Configuration Helper

This script helps you configure Kodiak to use your preferred LLM provider.
Run this script to interactively set up your LLM configuration.
"""

import os
import sys
from pathlib import Path


def main():
    print("🐻 Kodiak LLM Configuration Helper")
    print("=" * 40)
    print()
    
    # Available providers
    providers = {
        "1": {
            "name": "Google Gemini",
            "provider": "gemini",
            "models": {
                "1": "gemini/gemini-1.5-pro",
                "2": "gemini/gemini-1.5-flash"
            },
            "api_key_env": "GOOGLE_API_KEY",
            "description": "Google's latest AI model, excellent for reasoning and code analysis"
        },
        "2": {
            "name": "OpenAI GPT",
            "provider": "openai", 
            "models": {
                "1": "openai/gpt-4",
                "2": "openai/gpt-4-turbo",
                "3": "openai/gpt-3.5-turbo"
            },
            "api_key_env": "OPENAI_API_KEY",
            "description": "OpenAI's GPT models, proven performance for AI applications"
        },
        "3": {
            "name": "Anthropic Claude",
            "provider": "claude",
            "models": {
                "1": "claude-3-5-sonnet-20241022",
                "2": "claude-3-opus-20240229"
            },
            "api_key_env": "ANTHROPIC_API_KEY", 
            "description": "Anthropic's Claude models, excellent for security analysis"
        }
    }
    
    # Choose provider
    print("Choose your LLM provider:")
    for key, provider in providers.items():
        print(f"{key}. {provider['name']} - {provider['description']}")
    print()
    
    provider_choice = input("Enter your choice (1-3): ").strip()
    if provider_choice not in providers:
        print("❌ Invalid choice. Exiting.")
        return
    
    selected_provider = providers[provider_choice]
    print(f"\n✅ Selected: {selected_provider['name']}")
    print()
    
    # Choose model
    print("Choose your model:")
    for key, model in selected_provider['models'].items():
        print(f"{key}. {model}")
    print()
    
    model_choice = input(f"Enter your choice (1-{len(selected_provider['models'])}): ").strip()
    if model_choice not in selected_provider['models']:
        print("❌ Invalid choice. Exiting.")
        return
    
    selected_model = selected_provider['models'][model_choice]
    print(f"✅ Selected model: {selected_model}")
    print()
    
    # Get API key
    api_key_env = selected_provider['api_key_env']
    print(f"Enter your {selected_provider['name']} API key:")
    print(f"(This will be stored as {api_key_env})")
    api_key = input("API Key: ").strip()
    
    if not api_key:
        print("❌ API key is required. Exiting.")
        return
    
    print()
    
    # Generate .env file
    env_content = f"""# Kodiak LLM Configuration
# Generated by configure_llm.py

# LLM Provider Configuration
KODIAK_LLM_PROVIDER={selected_provider['provider']}
KODIAK_LLM_MODEL={selected_model}
{api_key_env}={api_key}

# LLM Settings
KODIAK_LLM_TEMPERATURE=0.1
KODIAK_LLM_MAX_TOKENS=4096

# Database Configuration (for Docker)
POSTGRES_SERVER=db
POSTGRES_USER=kodiak
POSTGRES_PASSWORD=kodiak_password
POSTGRES_DB=kodiak_db
POSTGRES_PORT=5432

# Application Settings
KODIAK_DEBUG=false
KODIAK_LOG_LEVEL=INFO
KODIAK_ENABLE_SAFETY=true
KODIAK_MAX_AGENTS=5
KODIAK_TOOL_TIMEOUT=300
KODIAK_ENABLE_HIVE_MIND=true
"""
    
    # Write .env file
    env_path = Path(".env")
    if env_path.exists():
        backup_path = Path(".env.backup")
        print(f"⚠️  Backing up existing .env to {backup_path}")
        env_path.rename(backup_path)
    
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print("✅ Configuration saved to .env")
    print()
    
    # Show next steps
    print("🚀 Next Steps:")
    print("1. Start Kodiak with: docker-compose up --build")
    print("2. Access the frontend at: http://localhost:3000")
    print("3. API will be available at: http://localhost:8000")
    print()
    
    # Show environment variables for manual setup
    print("📋 Environment Variables (for manual setup):")
    print(f"export KODIAK_LLM_PROVIDER={selected_provider['provider']}")
    print(f"export KODIAK_LLM_MODEL={selected_model}")
    print(f"export {api_key_env}={api_key}")
    print()
    
    print("🎯 Your Kodiak is now configured with:")
    print(f"   Provider: {selected_provider['name']}")
    print(f"   Model: {selected_model}")
    print(f"   Ready for deployment! 🐻")


if __name__ == "__main__":
    main()